/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three'
import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

const Globe = (props) => {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/models/globe.glb')
//   const { actions } = useAnimations(animations, group)

  useFrame(() => {
    if (group.current) {
      group.current.rotation.z -= 0.005
    }    
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_Model">
          <group
            name="arbol007_36"
            position={[0.851, 0.605, -0.005]}
            rotation={[0.173, 0.354, -1.1]}
            scale={0.011}>
            <mesh
              name="Object_64"
              castShadow
              receiveShadow
              geometry={(nodes.Object_64 as THREE.Mesh).geometry}
              material={materials.vegetacin}
            />
          </group>
          <group
            name="Armature001_10"
            position={[0.564, 0.451, 0.62]}
            rotation={[0.708, -0.369, -0.737]}
            scale={0.01}>
            <group name="GLTF_created_0">
              <group name="colaBallena001_9" />
              <skinnedMesh
                name="Object_15"
                geometry={nodes.Object_15.geometry}
                material={materials.ballena}
                skeleton={nodes.Object_15.skeleton}
              />
              <primitive object={nodes.GLTF_created_0_rootJoint} />
            </group>
          </group>
          <group
            name="Armature002_17"
            position={[-0.846, -0.218, -0.378]}
            rotation={[2.298, 0.497, 1.648]}
            scale={0.01}>
            <group name="GLTF_created_1">
              <group name="colaBallena002_16" />
              <skinnedMesh
                name="Object_25"
                geometry={nodes.Object_25.geometry}
                material={materials.ballena}
                skeleton={nodes.Object_25.skeleton}
              />
              <primitive object={nodes.GLTF_created_1_rootJoint} />
            </group>
          </group>
          <group
            name="Armature003_24"
            position={[0.43, -0.474, -0.704]}
            rotation={[-0.216, 1.029, -1.973]}
            scale={0.01}>
            <group name="GLTF_created_2">
              <group name="colaBallena003_23" />
              <skinnedMesh
                name="Object_35"
                geometry={nodes.Object_35.geometry}
                material={materials.ballena}
                skeleton={nodes.Object_35.skeleton}
              />
              <primitive object={nodes.GLTF_created_2_rootJoint} />
            </group>
          </group>
          <group
            name="barco009_3"
            position={[0.848, 0.333, 0.4]}
            rotation={[-1.408, -0.59, -1.937]}
            scale={0.01}>
            <mesh
              name="Object_10"
              castShadow
              receiveShadow
              geometry={nodes.Object_10.geometry}
              material={materials['Atlas.2']}
            />
          </group>
          <group
            name="barco_2"
            position={[0.644, -0.215, -0.719]}
            rotation={[-1.679, 0.395, 0.896]}
            scale={[0.015, 0.021, 0.016]}>
            <mesh
              name="Object_8"
              castShadow
              receiveShadow
              geometry={nodes.Object_8.geometry}
              material={materials.Atlas_1}
            />
          </group>
          <group
            name="edificio001_30"
            position={[0.969, 0.299, 0.303]}
            rotation={[0.057, -0.309, -1.25]}
            scale={[0.007, 0.018, 0.007]}>
            <mesh
              name="Object_52"
              castShadow
              receiveShadow
              geometry={nodes.Object_52.geometry}
              material={materials['Atlas.2']}
            />
          </group>
          <group name="Oceano_1">
            <mesh
              name="Object_4"
              castShadow
              receiveShadow
              geometry={nodes.Object_4.geometry}
              material={materials.agua}
            />
            <group name="tierra_0" scale={0.996}>
              <mesh
                name="Object_6"
                castShadow
                receiveShadow
                geometry={nodes.Object_6.geometry}
                material={materials.tierra}
              />
            </group>
          </group>
        </group>
        <mesh
          name="Object_56"
          castShadow
          receiveShadow
          geometry={nodes.Object_56.geometry}
          material={materials['ox-logo']}
        />
      </group>
    </group>
  )
}

useGLTF.preload("/models/globe.glb");
export default Globe;