/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: lavareefescape (https://sketchfab.com/lavareefescape)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sonic-generations-tornado-8dcf9c7432624234bafad3081e739b7e
Title: Sonic Generations - Tornado
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Plane = (props) => {
  const { nodes, materials } = useGLTF('/models/plane.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0.038, 0, 0]} scale={100}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh
            geometry={nodes.Object_12.geometry}
            material={materials.tornado_body}
            skeleton={nodes.Object_12.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_13.geometry}
            material={materials.tornado_light}
            skeleton={nodes.Object_13.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_14.geometry}
            material={materials.tornado_propeller}
            skeleton={nodes.Object_14.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_15.geometry}
            material={materials.tornado_body2}
            skeleton={nodes.Object_15.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_16.geometry}
            material={materials.tornado_handle}
            skeleton={nodes.Object_16.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_17.geometry}
            material={materials.tornado_PDA}
            skeleton={nodes.Object_17.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_18.geometry}
            material={materials.tornado_monitor}
            skeleton={nodes.Object_18.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_19.geometry}
            material={materials.tornado_glass}
            skeleton={nodes.Object_19.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_20.geometry}
            material={materials.tornado_propeller2}
            skeleton={nodes.Object_20.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_21.geometry}
            material={materials.tornado_logo2}
            skeleton={nodes.Object_21.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_22.geometry}
            material={materials.tornado_logo1}
            skeleton={nodes.Object_22.skeleton}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/plane.glb')
export default Plane;