
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three'
import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const Sonic = ({pose = 10, ...props}) => {
    const group = useRef<THREE.Group>(null);
    let { nodes, materials, animations } = useGLTF('/models/sonicwanim.glb');    
    animations = animations.slice(2, 14);
    const {ref, actions, names} = useAnimations(animations);
    const [index, setIndex] = React.useState(pose);
    useEffect(() => {     
        const action = actions[names[index]];        
        if (action) {            
            action.reset().fadeIn(0.5).play();            
        }     
        return () => {action ? action.fadeOut(0.5): null};
    }, [index, actions, names]);
  return (
    <group ref={ref} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <primitive object={nodes.mixamorigHips} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <skinnedMesh
          geometry={nodes.Object_10.geometry}
          material={materials.sonic_gm_shoes_belt}
          skeleton={nodes.Object_10.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_11.geometry}
          material={materials.sonic_gm_cloth}
          skeleton={nodes.Object_11.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_12.geometry}
          material={materials.sonic_gm_shoes_ring}
          skeleton={nodes.Object_12.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_13.geometry}
          material={materials.sonic_gm_mouth_duble}
          skeleton={nodes.Object_13.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_5.geometry}
          material={materials.sonic_gm_eyeL}
          skeleton={nodes.Object_5.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_6.geometry}
          material={materials.sonic_gm_eyeR}
          skeleton={nodes.Object_6.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_7.geometry}
          material={materials.sonic_gm_body}
          skeleton={nodes.Object_7.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_8.geometry}
          material={materials.sonic_gm_nose}
          skeleton={nodes.Object_8.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_9.geometry}
          material={materials.sonic_gm_shoes_red}
          skeleton={nodes.Object_9.skeleton}
        />        
      </group>
    </group>
  )
}

useGLTF.preload('/models/sonicwanim.glb')
export default Sonic;